### ISSUE TITLE
Definição da arquitetura básica inicial e tecnologias

### ISSUE THREAD

**Issue by vicenthy** [Camelooo/Arquitetutra#1]
Vamos definir aqui como o sistema ira funcionar e quais as tecnologias vamos utilizar inicialmente.

**Comment by tadeuespindolapalermo** [comment]
Show de bola! Parabéns pela iniciativa. :) 👍

**Comment by vicenthy** [comment]
# Galera vamos usar spring data jpa e mysql

**Comment by RobsonSales** [comment]
Acredito que temos que utilizar as ferramentas que estamos aprendendo e que estão em evidencia no mercado.
Ainda não aprendi o spring, mas concordo com o Vicente com relação as tecnologias.
De front-end, quais as tecnologias mais utilizadas no mercado que possamos colocar nesse projeto?

**Comment by fabianosf** [comment]
Que tal usarmos Spring boot ?

**Comment by vicenthy** [comment]
@fabianosf vamos usar spring boot sim, a dúvida no momento é se vamos usar Rest Full ou uma arquitetura mais abrangente como spring mvc ou joinfaces?

**Comment by fabianosf** [comment]
Tb nao saco de angular, mas to fazendo um curso e achando fácil.
Das tecnologias que vc flw vuejs, stenciljs ou react nao sei. 
Mais pra frente aprendo...com ctz... hehe... sei um pouco de jsf, html e css.... 
posso dar um gás melhor no backend e hibernate.....

**Comment by vicenthy** [comment]
Quem apoia iniciar com Spring MVC **da um joinha** aqui.

**Comment by vicenthy** [comment]
Quem apoia iniciar com JOINFACES da um joinha aqui.

**Comment by vicenthy** [comment]
Vamos iniciar com Spring MVC mesmo galera :)

**Comment by fabianosf** [comment]
Rsrs. Imaginei que fosse isso msm ! So estava esperando a galera falar !

**Comment by vicenthy** [comment]
Projeto criado https://github.com/Camelooo/cameloo-platform
